name: Sync to Public Repository

on:
  push:
    branches:
      - main # Or any branch you want to trigger the sync from

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up Git identity
        run: |
          git config --global user.email "you@example.com"  # Replace with your email
          git config --global user.name "Your Name"  # Replace with your name

      - name: Add public remote
        run: |
          git remote add public git@github.com:jagadeesh-max/public-to-sync.git

      - name: Pull changes from public repository
        run: |
          git fetch public
          git pull public main --rebase # Fetch and rebase remote changes if any

      - name: Sync to public repository
        run: |
          git push public main  # Push to the public repository (no --force)
